"""Stable request and execution limits shared by Coach workflows."""

COACH_DEFAULT_MAX_OUTPUT_TOKENS = 6_000
COACH_LONG_PLAN_MAX_OUTPUT_TOKENS = 32_000
COACH_BACKGROUND_HORIZON_DAYS = 7
COACH_TRAINING_CHANGE_LIMIT = 366
