const { test, expect } = require("@playwright/test");

test("@responsive nutrition diary and saved meals use the Coach and preserve consumption", async ({ page }) => {
  await page.goto("/#nutrition/diary");
  await expect(page.locator("#appShell")).toBeVisible();
  await expect(page.locator("#nutritionStatus")).not.toContainText("wird geladen");
  await expect(page.locator("#nutritionEntries .nutrition-card")).toHaveCount(0);
  await expect(page.locator("#nutritionTotals")).toContainText("– kcal");
  await page.locator('[data-nutrition-segment="meals"]').click();
  await page.locator("#nutritionDefine").click();
  await expect(page.locator("#messageInput")).toHaveValue(/wiederverwendbare Mahlzeit/);
  const send = async (text) => {
    await page.locator("#messageInput").fill(text);
    await page.locator("#messageInput").press("Enter");
    await expect.poll(() => page.evaluate(() => !state.busy && !state.chatServerOperationId && !state.chatRequest)).toBe(true);
  };
  await send("E2E nutrition: confirm meal");
  await expect(page.locator("#coachActionReview")).toBeVisible();
  await page.locator("#coachActionReview").getByRole("button", { name: "Mahlzeitvorlage speichern" }).click();
  await expect(page.locator("#coachActionReview")).toBeHidden();
  await page.evaluate(() => applyNavigationRoute("nutrition/meals", { historyMode: "push" }));
  await expect(page.locator("#nutritionTemplates .nutrition-card")).toHaveCount(1);
  await expect(page.locator("#nutritionTemplates")).toContainText("400 kcal");
  await expect(page.locator("#nutritionTemplates img")).toHaveCount(0);
  await page.locator('[data-nutrition-segment="diary"]').click();
  await expect(page.locator("#nutritionEntries .nutrition-card")).toHaveCount(0);
  await page.locator("#nutritionLog").click();
  await send("E2E nutrition: half portion");
  await page.evaluate(() => applyNavigationRoute("nutrition/diary", { historyMode: "push" }));
  await expect(page.locator("#nutritionEntries .nutrition-card")).toHaveCount(1);
  await expect(page.locator("#nutritionTotals")).toContainText("200 kcal");
  await page.locator('[data-nutrition-segment="meals"]').click();
  await page.locator("#nutritionTemplates").getByRole("button", { name: "Ändern beim Coach" }).click();
  await send("E2E nutrition: update meal");
  await expect(page.locator("#coachActionReview")).toBeVisible();
  await page.locator("#coachActionReview").getByRole("button", { name: "Mahlzeitvorlage speichern" }).click();
  await expect(page.locator("#coachActionReview")).toBeHidden();
  await page.evaluate(() => applyNavigationRoute("nutrition/meals", { historyMode: "push" }));
  await expect(page.locator("#nutritionTemplates")).toContainText("600 kcal");
  await page.locator("#nutritionTemplates").getByRole("button", { name: "Löschen beim Coach" }).click();
  await send("E2E nutrition: delete meal");
  await page.evaluate(() => applyNavigationRoute("nutrition/diary", { historyMode: "push" }));
  await expect(page.locator("#nutritionTotals")).toContainText("200 kcal");
  await page.locator("#nutritionPrevious").click();
  await expect(page.locator("#nutritionEntries .nutrition-card")).toHaveCount(0);
  await page.locator("#nutritionToday").click();
  await expect(page.locator("#nutritionEntries .nutrition-card")).toHaveCount(1);
  await page.evaluate(() => { document.querySelector("#messageInput").value = "Existing draft"; });
  await page.locator("#nutritionLog").click();
  await expect(page.locator("#messageInput")).toHaveValue("Existing draft");
  await page.locator("#messageInput").fill("");
  await page.goto("/#nutrition/diary");
  await expect(page.locator("#nutritionTotals")).toContainText("200 kcal");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
