const { test, expect } = require("@playwright/test");

test("@responsive current week report is shown automatically without controls", async ({ page, request }) => {
  let chatWrites = 0;
  page.on("request", (outgoing) => {
    if (outgoing.method() === "POST" && new URL(outgoing.url()).pathname.startsWith("/api/chat")) chatWrites += 1;
  });
  expect((await request.get("/api/fixture/activity")).ok()).toBeTruthy();
  await page.goto("/#analysis/review");
  await expect(page.locator("#appShell")).toBeVisible();
  const report = page.locator("#trainingReport");
  await expect(report.getByRole("img", { name: "Trainingsbelastung · aktuelle Woche" })).toBeVisible();
  await expect(report.getByRole("img", { name: "Trainingsbelastung · letzte 8 Wochen" })).toBeVisible();
  await expect(report.locator(".weekly-chart svg")).toHaveCount(2);
  expect((await report.locator(".weekly-chart svg").first().boundingBox()).height).toBeLessThan(350);
  const preserved = await page.evaluate(() => {
    const chart = document.querySelector("#trainingReport svg");
    renderAnalysisHistory(state.data.performance?.history);
    renderPersonalRecovery(state.data.performance?.personal_recovery);
    return chart === document.querySelector("#trainingReport svg");
  });
  expect(preserved).toBe(true);
  await expect(report.locator("svg [data-day]")).toHaveCount(7);
  await expect(report.locator("svg [data-week]")).toHaveCount(8);
  await expect(report.locator("svg rect")).toHaveCount(0);
  await expect(report.locator("svg [data-activity]")).toHaveCount(1);
  await expect(report.locator(".weekly-metrics > div")).toHaveCount(3);
  await expect(report.locator("input, select, button, details, summary")).toHaveCount(0);
  await expect(report.getByRole("heading", { name: "Vorperiode", exact: true })).toHaveCount(0);
  await expect(report.getByRole("heading", { name: "Schlüsseleinheiten nach gemessener Belastung", exact: true })).toHaveCount(0);
  const current = await (await request.get("/api/analysis/report")).json();
  expect(current.days).toBe(7);
  expect(current.daily.flatMap(day => day.activities)).toHaveLength(1);
  expect(current.weekly_load).toHaveLength(8);
  expect(current.daily[0].cumulative_training_load.value).toBe(current.daily[0].activities.length ? 50 : 0);
  await expect(report.locator(".weekly-chart").first().locator(".weekly-load-line")).toHaveCount(current.daily.filter(day => !day.future).length - 1);
  expect(current.weekly_load[7].training_load.value).toBe(50);
  expect(current.weekly_load[7].partial_period).toBe(true);
  await expect(report.locator("svg [data-activity] text")).toHaveText("Rad");
  await expect(report.locator(".weekly-chart").first()).not.toContainText("Synthetic ride");
  const marker = report.locator("svg [data-day][role=button]").last();
  await marker.locator("circle").last().click();
  const tooltip = report.locator('.analysis-info-tooltip:popover-open');
  await expect(tooltip).toContainText("Wochenbelastung: 50");
  await expect(tooltip).toContainText("Radfahren");
  await expect(tooltip.locator("img")).toHaveCount(0);
  await page.keyboard.press("Escape");
  await marker.focus();
  await page.keyboard.press("Enter");
  await expect(tooltip).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(report.locator(".weekly-day-sessions")).toHaveCount(0);
  await expect(report.getByText("Laufende Woche noch unvollst\u00e4ndig.", { exact: true })).toHaveCount(0);
  await expect(report.getByText(/absolvierte Einheiten/)).toHaveCount(0);
  expect(current.sport).toBe("all");
  const weekStart = new Date(`${current.start}T12:00:00Z`);
  expect(weekStart.getUTCDay()).toBe(1);
  const formatDate = (value) => value.split("-").reverse().join(".");
  await expect(report.getByRole("heading", { name: `Aktuelle Woche: ${formatDate(current.start)} – ${formatDate(current.end)}` })).toBeVisible();
  await expect(page.locator("[data-analysis-segment=review]")).toHaveText("Woche");
  await expect(page.locator("#analysisPerformanceSegment")).toBeHidden();
  await expect(page.locator("[data-analysis-segment=review]")).toHaveAttribute("aria-current", "page");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect(chatWrites).toBe(0);
});

test("@responsive analysis sections preserve report placement through browser history", async ({ page }) => {
  await page.goto("/#analysis/performance");
  await expect(page.locator("#appShell")).toBeVisible();
  await page.evaluate(async () => { await applyNavigationRoute("analysis/performance", { historyMode: "replace" }); });
  await expect(page.locator("#trainingReport")).toBeHidden();
  await expect(page.locator("#sessionPerformance")).toBeVisible();
  await page.locator("[data-analysis-segment=review]").click();
  await expect(page.locator("#trainingReport")).toBeVisible();
  await expect(page.locator("#sessionPerformance")).toBeHidden();
  await page.locator("[data-analysis-segment=recovery]").click();
  await expect(page.locator("#trainingReport")).toBeHidden();
  await expect(page.locator("#personalRecovery")).toBeVisible();
  await page.goBack();
  await expect(page.locator("#trainingReport")).toBeVisible();
  await expect(page.locator("[data-analysis-segment=review]")).toHaveAttribute("aria-current", "page");
});
